### ISSUE TITLE
Modify Network Polytope Diagrams According to Network Structure

### ISSUE THREAD

**Issue by levinwil** [levinwil/NeuralPolytopes#1]
1. Reflect network architecture structure in diagram, with 3 layer 0 nodes and 3 layer 1 nodes
2. Change contour plot colors to be greyscale (with no negative regions)
3. Draw arrows between nodes to show weights (i.e. reflect the current purple/green)
4. Plot all the polytopes in the final (and potentially intermediate) diagrams

**Comment by jovo** [comment]
https://nbviewer.jupyter.org/github/levinwil/NeuralPolytopes/blob/master/Neural_Polytopes.ipynb

**Comment by levinwil** [comment]
Closing per the above notebook
